Notebook that helped me figure out topics as I created my LLM, might remove since it's not really polished..

In [2]:
import sys
import os
parent_directory = os.path.dirname(os.getcwd())
sys.path.append(parent_directory)

### Attention
Given an input sequence of three tokens, with embedding dimension of 2:
$$
X = \begin{bmatrix}
x_{1,1} & x_{1,2} \\
x_{2,1} & x_{2,2} \\
x_{3,1} & x_{3,2}
\end{bmatrix}
$$

And Q, K, and V learnable weights:
$$
W_Q = \begin{bmatrix}
w^{q}_{1,1} & w^{q}_{1,2} \\
w^{q}_{2,1} & w^{q}_{2,2}
\end{bmatrix}
\quad
W_K = \begin{bmatrix}
w^{k}_{1,1} & w^{k}_{1,2} \\
w^{k}_{2,1} & w^{k}_{2,2}
\end{bmatrix}
\quad
W_V = \begin{bmatrix}
w^{v}_{1,1} & w^{v}_{1,2} \\
w^{v}_{2,1} & w^{v}_{2,2}
\end{bmatrix}
$$


$$
Q = X \times W_Q
$$

$$
Q = \begin{bmatrix}
x_{1,1} & x_{1,2} \\
x_{2,1} & x_{2,2} \\
x_{3,1} & x_{3,2}
\end{bmatrix}
\times
\begin{bmatrix}
w^{q}_{1,1} & w^{q}_{1,2} \\
w^{q}_{2,1} & w^{q}_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
x_{1,1}w^{q}_{1,1} + x_{1,2}w^{q}_{2,1} & x_{1,1}w^{q}_{1,2} + x_{1,2}w^{q}_{2,2} \\
x_{2,1}w^{q}_{1,1} + x_{2,2}w^{q}_{2,1} & x_{2,1}w^{q}_{1,2} + x_{2,2}w^{q}_{2,2} \\
x_{3,1}w^{q}_{1,1} + x_{3,2}w^{q}_{2,1} & x_{3,1}w^{q}_{1,2} + x_{3,2}w^{q}_{2,2}
\end{bmatrix}
$$

$$
Q = \begin{bmatrix}
q_{1,1} & q_{1,2} \\
q_{2,1} & q_{2,2} \\
q_{3,1} & q_{3,2}
\end{bmatrix}
$$


$$
K = X \times W_K \quad = \quad \begin{bmatrix}
k_{1,1} & k_{1,2} \\
k_{2,1} & k_{2,2} \\
k_{3,1} & k_{3,2}
\end{bmatrix}
$$

$$
V = X \times W_V \quad = \quad \begin{bmatrix}
v_{1,1} & v_{1,2} \\
v_{2,1} & v_{2,2} \\
v_{3,1} & v_{3,2}
\end{bmatrix}
$$


Attention Score:
$$
A\_S = Q \times K^T
$$

$$
A\_S = \begin{bmatrix}
q_{1,1} & q_{1,2} \\
q_{2,1} & q_{2,2} \\
q_{3,1} & q_{3,2}
\end{bmatrix}
\times
\begin{bmatrix}
k_{1,1} & k_{2,1} & k_{3,1} \\
k_{1,2} & k_{2,2} & k_{3,2}
\end{bmatrix}
=
\begin{bmatrix}
q_{1,1}k_{1,1} + q_{1,2}k_{1,2} & q_{1,1}k_{2,1} + q_{1,2}k_{2,2} & q_{1,1}k_{3,1} + q_{1,2}k_{3,2} \\
q_{2,1}k_{1,1} + q_{2,2}k_{1,2} & q_{2,1}k_{2,1} + q_{2,2}k_{2,2} & q_{2,1}k_{3,1} + q_{2,2}k_{3,2} \\
q_{3,1}k_{1,1} + q_{3,2}k_{1,2} & q_{3,1}k_{2,1} + q_{3,2}k_{2,2} & q_{3,1}k_{3,1} + q_{3,2}k_{3,2}
\end{bmatrix}
$$

$$
A\_S = \begin{bmatrix}
s_{1,1} & s_{1,2} & s_{1,3} \\
s_{2,1} & s_{2,2} & s_{2,3} \\
s_{3,1} & s_{3,2} & s_{3,3}
\end{bmatrix}
$$

Scale and Normalize attention scores:  
(softmax is applied across the features dimension)
$$
\text{Scaled, Normalized } A\_S = \text{softmax}\left(\frac{1}{\sqrt{2}} \begin{bmatrix}
s_{1,1} & s_{1,2} & s_{1,3} \\
s_{2,1} & s_{2,2} & s_{2,3} \\
s_{3,1} & s_{3,2} & s_{3,3}
\end{bmatrix}\right)
$$


Attention Weights
$$
\text{Attention Weights} = \text{Scaled, Normalized } A\_S
$$

$$
\text{Attention Weights} = \begin{bmatrix}
\alpha_{1,1} & \alpha_{1,2} & \alpha_{1,3} \\
\alpha_{2,1} & \alpha_{2,2} & \alpha_{2,3} \\
\alpha_{3,1} & \alpha_{3,2} & \alpha_{3,3}
\end{bmatrix}
$$


Attention Output:
$$
\text{Attention Output} = \text{Attention Weights} \times V
$$

$$
\text{Attention Output} = \begin{bmatrix}
\alpha_{1,1} & \alpha_{1,2} & \alpha_{1,3} \\
\alpha_{2,1} & \alpha_{2,2} & \alpha_{2,3} \\
\alpha_{3,1} & \alpha_{3,2} & \alpha_{3,3}
\end{bmatrix}
\times
\begin{bmatrix}
v_{1,1} & v_{1,2} \\
v_{2,1} & v_{2,2} \\
v_{3,1} & v_{3,2}
\end{bmatrix}
=
\begin{bmatrix}
\alpha_{1,1}v_{1,1} + \alpha_{1,2}v_{2,1} + \alpha_{1,3}v_{3,1} & \alpha_{1,1}v_{1,2} + \alpha_{1,2}v_{2,2} + \alpha_{1,3}v_{3,2} \\
\alpha_{2,1}v_{1,1} + \alpha_{2,2}v_{2,1} + \alpha_{2,3}v_{3,1} & \alpha_{2,1}v_{1,2} + \alpha_{2,2}v_{2,2} + \alpha_{2,3}v_{3,2} \\
\alpha_{3,1}v_{1,1} + \alpha_{3,2}v_{2,1} + \alpha_{3,3}v_{3,1} & \alpha_{3,1}v_{1,2} + \alpha_{3,2}v_{2,2} + \alpha_{3,3}v_{3,2}
\end{bmatrix}
$$


$$
\text{Attention Output} = O = \begin{bmatrix}
o_{1,1} & o_{1,2} \\
o_{2,1} & o_{2,2} \\
o_{3,1} & o_{3,2}
\end{bmatrix}
$$


Multi-head attention
$$
\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \dots, \text{head}_h) W^O
$$

$$
\text{head}_i = \text{Attention}(Q W_Q^{(i)}, K W_K^{(i)}, V W_V^{(i)}) = \text{softmax}\left(\frac{(Q W_Q^{(i)}) (K W_K^{(i)})^T}{\sqrt{d_k}}\right) (V W_V^{(i)})
$$


example of mulit-head attention
$$
\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \text{head}_2, \text{head}_3) W^O
$$

$$
\text{Concat}(\text{head}_1, \text{head}_2, \text{head}_3) =
\begin{bmatrix}
\text{head}_1 & \text{head}_2 & \text{head}_3
\end{bmatrix}
=
\begin{bmatrix}
h_{1,1} & h_{1,2} & h_{1,3} & h_{1,4} & h_{1,5} & h_{1,6} \\
h_{2,1} & h_{2,2} & h_{2,3} & h_{2,4} & h_{2,5} & h_{2,6} \\
h_{3,1} & h_{3,2} & h_{3,3} & h_{3,4} & h_{3,5} & h_{3,6}
\end{bmatrix}
$$

$$
\text{Attention Output} = \begin{bmatrix}
h_{1,1} & h_{1,2} & h_{1,3} & h_{1,4} & h_{1,5} & h_{1,6} \\
h_{2,1} & h_{2,2} & h_{2,3} & h_{2,4} & h_{2,5} & h_{2,6} \\
h_{3,1} & h_{3,2} & h_{3,3} & h_{3,4} & h_{3,5} & h_{3,6}
\end{bmatrix}
\times
\begin{bmatrix}
w_{1,1} & w_{1,2} & \dots & w_{1,d_{model}} \\
w_{2,1} & w_{2,2} & \dots & w_{2,d_{model}} \\
\vdots  & \vdots  & \ddots & \vdots \\
w_{6,1} & w_{6,2} & \dots & w_{6,d_{model}}
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
o_{1,1} & o_{1,2} & \dots & o_{1,d_{model}} \\
o_{2,1} & o_{2,2} & \dots & o_{2,d_{model}} \\
o_{3,1} & o_{3,2} & \dots & o_{3,d_{model}}
\end{bmatrix}
$$


## Rotary Positional Embedding (RoPE)

In [3]:
'''
RoPE (rotary positional embedding) -- spelled out.
Rotate token embedding pairs before attending. This means that the positional embedding will no longer be a learned parameter (or fixed sinusoidal), it is just a transformation of a token's embedding. This encodes positional information intrinsically within the token's embedding.

The rotation angle `theta_p` is set to `p * ω_k`, where `p` is the token's position in the sequence and `w_k` is a frequency associated with each pair of dimensions.
`w_k` decreases exponentially with increasing dimension index, meaning lower-indexed pairs of dimensions rotate more than higher-indexed ones.
This design allows RoPE to capture relative positional information across different dimensions in a smooth, continuous manner.
'''

import math
import torch

def rope_1d_slow(p, embedding):
    # p: index-position of token in sequence
    # embedding: embedding representation of token

    dim = len(embedding)
    assert dim % 2 == 0

    def w_k(k):
        return 1 / (10_000 ** (2*k/dim))
    
    def theta_p(k):
        # k: index-position of embedding-pair for tokem embedding
        return p * w_k(k)
    
    transformation = torch.zeros(dim//2, 2)

    for i in range(0, len(embedding), 2):
        x_i_0 = embedding[i]
        x_i_1 = embedding[i+1]
        theta_p_val = theta_p(i//2)
        cos = math.cos(theta_p_val)
        sin = math.sin(theta_p_val)
        rotation = torch.tensor([
            [cos, -1*sin],
            [sin, cos]
        ])
        x = torch.tensor([x_i_0, x_i_1])
        transformation[i//2, :] = torch.matmul(rotation, x)

    return transformation.view(-1)

def rope_1d_faster(p, embedding):
    dim = len(embedding)
    assert dim % 2 == 0

    indices = torch.arange(0, dim // 2)
    w_k = 1 / (10_000 ** (2 * indices / dim))
    cosine = torch.cos(p * w_k)
    cosine = cosine.repeat_interleave(2)
    sine = torch.sin(p * w_k)
    sine = sine.repeat_interleave(2)
    
    x = embedding
    x_shifted = torch.empty(len(embedding), dtype=embedding.dtype)
    x_shifted[1::2], x_shifted[::2] = embedding[::2], -embedding[1::2]

    return x * cosine + x_shifted * sine

def rope_multi_head_broadcasting(att_comp):
    # att_comp: attention component, either Q or K.
    # Perform RoPE on each attention head of att_comp
    # expected shape (Batch, Sequence, Head, Head Dimension).
    # Use broadcasting along the Batch and Sequence dimension to save memory.
    B, S, H, HD = att_comp.shape
    assert HD % 2 == 0

    ind_emb = torch.arange(0, HD // 2) # embedding-pairs indices
    w_k = 1 / (10_000 ** (2 * ind_emb / HD))

    # Expand w_k for each token in Sequence and perform `p * w_k`
    w_k = w_k.view(1, -1)
    w_k = w_k.repeat_interleave(S, 0)
    ind_tok = torch.arange(S).unsqueeze(1).repeat(1, w_k.shape[1]) # token indices
    w_k = w_k * ind_tok

    # Get cosine rot. values
    cosine = torch.cos(w_k)
    cosine = cosine.repeat_interleave(2, -1) # repeat for embedding pairs
    # reshape to B=1, S, H=1, HD
    cosine = cosine.view(1, S, 1, HD)

    # Get sine rot. values
    sine = torch.sin(w_k)
    sine = sine.repeat_interleave(2, -1) # repeat for embedding pairs
    sine = sine.repeat_interleave(H, 0) # repeat for all attn heads
    # reshape to B, S, H, HD
    sine = sine.view(1, S, H, HD)
    sine = sine.repeat_interleave(B, 0)

    x = att_comp
    x_shifted = torch.empty(att_comp.shape, dtype=att_comp.dtype)
    x_shifted[...,1::2], x_shifted[...,::2] = att_comp[...,::2], -att_comp[...,1::2]

    return x * cosine + x_shifted * sine

In [4]:
# Full RoPE implementation
B, S, H, HD = 2, 3, 2, 8
q = torch.empty(B, S, H, HD)
q[:,:,:,:] = torch.tensor([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
rope_multi_head_broadcasting_res = rope_multi_head_broadcasting(q)
print(rope_multi_head_broadcasting_res)

tensor([[[[ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,
            0.7000],
          [ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,
            0.7000]],

         [[-0.0841,  0.0540,  0.1691,  0.3185,  0.3950,  0.5040,  0.5993,
            0.7006],
          [-0.0841,  0.0540,  0.1691,  0.3185,  0.3950,  0.5040,  0.5993,
            0.7006]],

         [[-0.0909, -0.0416,  0.1364,  0.3338,  0.3899,  0.5079,  0.5986,
            0.7012],
          [-0.0909, -0.0416,  0.1364,  0.3338,  0.3899,  0.5079,  0.5986,
            0.7012]]],


        [[[ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,
            0.7000],
          [ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,
            0.7000]],

         [[-0.0841,  0.0540,  0.1691,  0.3185,  0.3950,  0.5040,  0.5993,
            0.7006],
          [-0.0841,  0.0540,  0.1691,  0.3185,  0.3950,  0.5040,  0.5993,
            0.7006]],

         [[-0.0909, -0.0416,  0.1364, 

In [5]:
# Simpler RoPE implementations
rope_1d_slow_res = rope_1d_slow(2, [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
print(rope_1d_slow(2, [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7]))
print(rope_1d_faster(2, torch.tensor([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])))

tensor([-0.0909, -0.0416,  0.1364,  0.3338,  0.3899,  0.5079,  0.5986,  0.7012])
tensor([-0.0909, -0.0416,  0.1364,  0.3338,  0.3899,  0.5079,  0.5986,  0.7012])


In [7]:
# sanity check that naive implementation
print(torch.equal(rope_multi_head_broadcasting_res[0,2,0,:], rope_1d_slow_res))

False


In [8]:
def rotate_half(x):
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)

B, S, H, HD = 2, 3, 2, 8
q = torch.empty(B, S, H, HD)
q[:,:,:,:] = torch.tensor([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
q = rotate_half(q)
print(q)

tensor([[[[-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000],
          [-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000]],

         [[-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000],
          [-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000]],

         [[-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000],
          [-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000]]],


        [[[-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000],
          [-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000]],

         [[-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000],
          [-0.4000, -0.5000, -0.6000, -0.7000,  0.0000,  0.1000,  0.2000,
            0.3000]],

         [[-0.4000, -0.5000, -0.6000, 